name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: steinberg-download-assistant-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      # - name: anydesk
      #   shell: cmd
      #   run: |
      #     curl -L -O -J https://download.anydesk.com/AnyDesk.exe &&^
      #     .\AnyDeskStart.cmd
          
      - name: installer
        shell: cmd
        run: |
          curl -L -J --output installer.exe "https://download.steinberg.net/automated_updates/sda-selfupdate/releases/absolute-downloader-1.35.0-b554-ee1498e0-5fb5-4bfd-8dcd-5df7a845d69e/win/Steinberg_Download_Assistant_1.35.0_Installer_win.exe" &&^
          dir
          
      - shell: cmd
        run: |
          set __COMPAT_LAYER=RUNASINVOKER
          installer.exe --mode unattended
          cd /d C:\Program Files (x86)\Steinberg\Download Assistant &&^
          dir /s

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "C:/Program Files (x86)/Steinberg/Download Assistant"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "C:/Program Files (x86)/Steinberg/Download Assistant/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

